# Generated by Django 2.2.10 on 2020-03-27 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='categorie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Application_categorie', to='blog.CategorieApplication'),
        ),
        migrations.AddField(
            model_name='application',
            name='tag',
            field=models.ManyToManyField(null=True, related_name='tag_application', to='blog.Tag'),
        ),
    ]
